name: run python file 
on: [push,workflow_dispatch]
jobs:
  fetchfiles:
    runs-on: ubuntu-latest
    steps:
      - name: start fetch the repo 
        run: echo "initializing for fetching"
      - name: fetching now
        uses: actions/checkout@v5
        with: 
          sparse-checkout: |
            name.py
      - name: run file
        run: python3 name.py
      - name: expression testing
        run: echo "${{toJSON(github) }}"
